Flask_Learning/News_Website/info/modules/news/__init__.py
from flask import Blueprint
news_blue = Blueprint("news",__name__,url_prefix="/news")

from . import views

Flask_Learning/News_Website/info/modules/news/views.py
from flask import render_template, make_response, g, jsonify, request, current_app

from info import db
from info.models import News, Comment, CommentLike, User
from info.utils.common import user_login_data
from info.utils.response_code import RET
from . import news_blue


@news_blue.route("/<int:news_id>")
@user_login_data
def news_detail(news_id):
    user = g.user
    """查询右边热门新闻的数据"""
    news_model = News.query.order_by(News.clicks.desc()).limit(10)
    news_clicks = []
    for news in news_model:
        news_clicks.append(news.to_dict())

    """根据新闻ID查询当前新闻详情里面的数据"""
    news = News.query.get(news_id)
    # 点击量加一
    news.clicks += 1



    """收藏新闻"""
    is_collection = False
    is_followed = False
    if user:
        if news in user.collection_news:
            is_collection = True
    if news.user and user:
        if news.user in user.followed:
            is_followed = True




    # 获取评论
    comments = Comment.query.filter(Comment.news_id==news_id).all()
    comment_list = []
    for item in comments:
        comment_list.append(item.to_dict())

    """获取新闻的评论信息"""
    comments = Comment.query.filter(Comment.news_id==news_id).all()
    comment_likes = []
    comment_like_ids = []
    if user:
        comments_list = CommentLike.query.filter(CommentLike.user_id==user.id).all()
        comment_like_ids = [comment_like.comment_id for comment_like in comment_likes]
    comments_list = []
    for item in comments:
        item_dict = item.to_dict()
        item_dict["is_like"] = False
        if item.id in comment_like_ids:
            item_dict["is_like"] = True
        comments_list.append(item_dict)



    data = {
        "user_info": user.to_dict() if user else None,
        "click_news_list": news_clicks,
        "news": news.to_dict(),
        "is_collected": is_collection,
        "comments":comments_list,
        "is_followed":is_followed
    }
    return render_template("news/detail.html", data=data)

@news_blue.route("/news_collect",methods=["POST"])
@user_login_data
def news_collect():
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR,errmsg="请登录")
    news_id = request.json.get("news_id")
    action = request.json.get("action")
    news = News.query.get(news_id)

    if not news:
        return jsonify(errno=RET.NODATA,errmsg="没有此数据")
    if action == "collect":
        user.collection_news.append(news)
    else:
        user.collection_news.remove(news)

    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
    return jsonify(errno=RET.OK,errmsg="收藏成功")


@news_blue.route("/news_comment",methods=["POST"])
@user_login_data
def news_comment():
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR,errmsg="请登录")
    news_id = request.json.get("news_id")
    comment_str = request.json.get("comment")
    parent_id = request.json.get("parent_id")

    news = News.query.get(news_id)
    comment = Comment()
    comment.user_id = user.id
    comment.news_id = news_id
    comment.content = comment_str
    if parent_id:
        comment.parent_id = parent_id

    db.session.add(comment)
    db.session.commit()

    return jsonify(errno=RET.OK,errmsg="评论成功",data=comment.to_dict())




@news_blue.route("/comment_like",methods=["POST"])
@user_login_data
def comment_like():
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR,errmsg="请登录")
    comment_id = request.json.get("comment_id")
    news_id = request.json.get("news_id")
    action = request.json.get("action")
    comment = Comment.query.get(comment_id)
    if action == "add":
        comment_like = CommentLike.query.filter_by(comment_id=comment_id,user_id = user.id).first()
        if not comment_like:
            comment_like = CommentLike()
            comment_like.comment_id = comment_id
            comment_like.user_id = user.id
            db.session.add(comment_like)

            comment.like_count += 1
            db.session.commit()

    else:
        comment_like = CommentLike.query.filter_by(comment_id = comment_id,user_id = user.id).first()
        if comment_like:
            db.session.delete(comment_like)
            comment.like_count -= 1
            db.session.commit()
    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR,errmsg="操作失败")
    return jsonify(errno=RET.OK,errmsg="操作成功")



@news_blue.route("/followed_user",methods=["POST"])
@user_login_data
def followed_user():
    if not g.user:
        return jsonify(errno=RET.SESSIONERR,errmsg="未登录")
    user_id = request.json.get("user_id")
    action = request.json.get("action")

    if not all([user_id,action]):
        return jsonify(errno=RET.PARAMERR,errmsg="参数不全")
    if action not in ("follow","unfollow"):
        return jsonify(errno=RET.PARAMERR,errmsg="action参数错误")
    try:
        target_user=User.query.get(user_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR,errmsg="数据库查询失败")
    if not target_user:
        return jsonify(errno=RET.NODATA,errmsg="未查询到用户数据")
    if action == "follow":
        if target_user.followers.filter(User.id==g.user.id).count()>0:
            return jsonify(errno=RET.DATAEXIST,errmsg="已关注")
        target_user.followers.append(g.user)
    else:
        if target_user.followers.filter(User.id==g.user.id).count()>0:
            target_user.followers.remove(g.user)

    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR,errmsg="数据保存错误")
    return jsonify(errno=RET.OK,errmsg="操作成功")

Flask_Learning/News_Website/info/modules/user/__init__.py
from flask import Blueprint
profile_blue = Blueprint("profile",__name__,url_prefix="/user")

from . import views

Flask_Learning/News_Website/info/modules/user/views.py
from flask import g, request, render_template, session, jsonify, redirect, current_app, abort

from info.models import Category, News, User
from info.utils.image_storage import storage

from info import db, constants
from info.utils.common import user_login_data
from info.utils.response_code import RET
from . import profile_blue


@profile_blue.route("/info")
@user_login_data
def get_user_info():
    user = g.user
    if not user:
        return redirect('/')
    data = {
        "user_info": user.to_dict(),
    }
    return render_template("news/user.html", data=data)


@profile_blue.route("/base_info", methods=["GET", "POST"])
@user_login_data
def base_info():
    user = g.user
    if request.method == "GET":
        data = {
            "user_info": user.to_dict() if user else None
        }
        return render_template("news/user_base_info.html", data=data)
    nick_name = request.json.get("nick_name")
    signature = request.json.get("signature")
    gender = request.json.get("gender")
    print(gender)

    user.nick_name = nick_name
    user.signature = signature
    user.gender = gender
    db.session.commit()
    session["nick_name"] = user.nick_name
    return jsonify(errno=RET.OK, errmsg="修改成功")


@profile_blue.route("/pic_info", methods=["GET", "POST"])
@user_login_data
def pic_info():
    user = g.user
    if request.method == "GET":
        data = {
            "user_info": user.to_dict() if user else None
        }
        return render_template("news/user_pic_info.html", data=data)
    avatar_file = request.files.get("avatar").read()
    key = storage(avatar_file)
    user.avatar_url = key
    db.session.commit()
    data = {
        "avatar_url": constants.QINIU_DOMIN_PREFIX + key
    }

    return jsonify(errno=RET.OK, errmsg="上传成功", data=data)


@profile_blue.route("/pass_info", methods=["POST", "GET"])
@user_login_data
def pass_info():
    if request.method == "GET":
        return render_template("news/user_pass_info.html")
    old_password = request.json.get("old_password")
    new_password = request.json.get("new_password")
    user = g.user
    if not user.check_password(old_password):
        return jsonify(errno=RET.PARAMERR, errmsg="密码有误")
    user.password = new_password
    db.session.commit()
    return jsonify(errno=RET.OK, errmsg="修改成功")


@profile_blue.route("/collection")
@user_login_data
def collection():
    page = request.args.get("p", 1)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    user = g.user
    paginate = user.collection_news.paginate(page, 5, False)
    items = paginate.items
    current_page = paginate.page
    total_page = paginate.pages
    collections = []
    for item in items:
        collections.append(item.to_dict())

    data = {
        "collections": collections,
        "current_page": current_page,
        "total_page": total_page
    }
    return render_template("news/user_collection.html", data=data)


@profile_blue.route("/news_release", methods=["POST", 'GET'])
@user_login_data
def news_release():
    if request.method == "GET":
        category_list = Category.query.all()
        categories = []
        for category in category_list:
            categories.append(category.to_dict())
        categories.pop(0)
        data = {"categories": categories}
        return render_template("news/user_news_release.html", data=data)

    # 发布新闻
    title = request.form.get("title")
    if not title:
        return jsonify(errno=RET.PARAMERR, errmsg="title参数输入错误")

    category_id = request.form.get("category_id")
    if not category_id:
        return jsonify(errno=RET.PARAMERR, errmsg="category_id参数输入错误")

    digest = request.form.get("digest")
    if not digest:
        return jsonify(errno=RET.PARAMERR, errmsg="digest参数输入错误")

    index_image = request.files.get("index_image")
    if not index_image:
        return jsonify(errno=RET.PARAMERR, errmsg="index_image参数输入错误")

    content = request.form.get("content")
    if not content:
        return jsonify(errno=RET.PARAMERR, errmsg="content参数输入错误")

    if not all([title, category_id, digest, index_image, content]):
        return jsonify(errno=RET.PARAMERR, errmsg="参数存在空白")

    index_image = index_image.read()
    key = storage(index_image)
    user = g.user
    news = News()
    news.title = title
    news.source = "个人来源"
    news.digest = digest
    news.content = content
    news.index_image_url = constants.QINIU_DOMIN_PREFIX + key
    news.category_id = category_id
    news.user_id = user.id

    # 1 表示审核中
    news.status = 1
    db.session.add(news)
    db.session.commit()
    return jsonify(errno=RET.OK, errmsg="发布成功")


@profile_blue.route("/news_list")
@user_login_data
def news_list():
    page = request.args.get("p", 1)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
    user = g.user
    paginate = news = News.query.filter_by(user_id=user.id).paginate(page, 10, False)
    items = paginate.items
    total_page = paginate.pages
    current_page = paginate.page

    news_release_list = []
    for item in items:
        news_release_list.append(item.to_review_dict())

    data = {
        "news_list": news_release_list,
        "current_page": current_page,
        "total_page": total_page
    }

    return render_template("news/user_news_list.html", data=data)


@profile_blue.route("/user_follow")
@user_login_data
def user_follow():
    p = request.args.get("p", 1)
    try:
        p = int(p)
    except Exception as e:
        current_app.logger.error(e)
        p = 1

    user = g.user
    follows = []
    current_page = 1
    total_page = 1

    try:
        paginate = user.followed.paginate(p, constants.USER_FOLLOWED_MAX_COUNT, False)
        follows = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    user_dict_list = []
    for follow_user in follows:
        user_dict_list.append(follow_user.to_dict())
    data = {
        "users": user_dict_list,
        "total_page": total_page,
        "current_page": current_page
    }
    return render_template("news/user_follow.html", data=data)

@profile_blue.route("/other_info")
@user_login_data
def other_info():
    user = g.user
    user_id = request.args.get("id")
    if not user_id:
        print("没有此ID")
        abort(404)
    other = None
    try:
        other = User.query.get(user_id)
        print("获取到用户id",other)
    except Exception as e:
        current_app.logger.error(e)
    if not other:
        abort(404)
    is_followed = False
    if g.user:
        if other.followers.filter(User.id==user.id).count()>0:
            is_followed = True

    data = {
        "user_info":user.to_dict(),
        "other_info":other.to_dict(),
        "is_followed":is_followed
    }
    return render_template("news/other.html",data=data)


@profile_blue.route("/other_news_list")
def other_news_list():
    p = request.args.get("p",1)
    user_id = request.args.get("user_id")
    try:
        p = int(p)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR,errmsg="参数错误")
    if not all([p,user_id]):
        return jsonify(errno=RET.PARAMERR,errmsg="参数错误")
    try:
        user = User.query.get(user_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR,errmsg="数据查询失败")
    if not user:
        return jsonify(errno=RET.NODATA,errmsg="用户不存在")
    try:
        paginate = News.query.filter(News.user_id==user.id).paginate(p,constants.OTHER_NEWS_PAGE_MAX_COUNT,False)
        other_news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据查询失败")
    news_dict_list = []
    for news_item in other_news_list:
        news_dict_list.append(news_item.to_review_dict())
    data = {
        "news_list":news_dict_list,
        "current_page":current_page,
        "total_page":total_page
    }

    return jsonify(errno=RET.OK,errmsg="ok",data=data)

Flask_Learning/News_Website/info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="/favicon.ico"/>
<link rel="bookmark" href="/favicon.ico"/>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block scriptBlock %}{% endblock %}
</head>
<body>
    <div class="header_con">
        <div class="header">
            <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
            {% block categoryBlock %}{% endblock %}
             {# 判断用户是否登录 #}
            {% if data.user_info %}
            {# 如果登录，则显示用户信息 #}
                <div class="user_login fr">
                    <img src="{% if data.user_info.avatar_url %}
                        {{ data.user_info.avatar_url }}
                    {% else %}../../static/news/images/person01.png{% endif %}" class="lgin_pic">
                    <a href="/user/info" id="nick_name">{{ data.user_info.nick_name }}</a>
                    <a href="javascript:;" onclick="logout()">退出</a>
                </div>
            {% else %}
            {# 如果没有登录，则显示登录注册按钮 #}
            <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
            </div>
             {% endif %}
            </div>
    </div>

    <div class="conter_con">

         {% block contentBlock %}
         {% endblock %}

        {% block rankBlock %}
        <div class="rank_con fr">
            {% block authorBlock %}
            {% endblock %}
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
            <ul class="rank_list">
                  {% for news in data.click_news_list %}
                     <li><span class="{{ loop.index0 | indexClass }}">{{ loop.index }}</span><a href="/news/{{ news.id }}">{{ news.title }}</a></li>
                  {% endfor %}
            </ul>
        </div>
        {% endblock %}
    </div>

    {% block footerBlock %}
        <div class="footer">
            <div class="footer_links">
                <a href="">关于我们</a>
                <span>|</span>
                <a href="">联系我们</a>
                <span>|</span>
                <a href="">招聘人才</a>
                <span>|</span>
                <a href="">友情链接</a>
            </div>
            <p class="copyright">
                CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
    电话：010-****888    京ICP备*******8号
            </p>
        </div>
    {% endblock %}

    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

Flask_Learning/News_Website/info/templates/news/index.html
{% extends "news/base.html" %}

{% block titleBlock %}
首页-新经资讯
{% endblock %}

{% block scriptBlock %}
<script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}

{% block categoryBlock %}
<ul class="menu fl">

     {% for category in data.categories %}
          <li class="{% if loop.index0 == 0 %}active{% endif %}" data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
{# 模版里面获取属性可以直接.但在Python中必须get()或则[]#}
     {% endfor %}

</ul>
{% endblock %}

{% block contentBlock %}
<ul class="list_con fl">

            {% for new in data.news_list %}
                <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">{{ data.news_list.title }}</a>
                <a href="#" class="news_detail fl">{{ data.news_list.digest }}</a>
                <div class="author_info fl">
                    <div class="author fl">
                        <img src="../../static/news/images/person.png" alt="author">
                        <a href="#">乐鸣</a>
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>

            {% endfor %}


        </ul>
{% endblock %}

{% block authorBlock %}

{% endblock %}

Flask_Learning/News_Website/info/templates/news/user.html
{% extends "news/base.html" %}

{% block titleBlock %}
用户中心
{% endblock %}

{% block scriptBlock %}
<script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>
{% endblock %}
{% block rankBlock %}

{% endblock %}

{% block contentBlock %}
<div class="user_menu_con fl">


            <div class="user_center_pic">
                <img src={% if data.user_info.avatar_url %}
                    {{ data.user_info.avatar_url }}
                {% else %}
                    "../../static/news/images/user_pic.png"
                {% endif %} alt="用户图片">
            </div>
           <div class="user_center_name">{{ data.user_info.nick_name }}</div>



			<ul class="option_list">
				<li class="active"><a href="/user/base_info" target="main_frame">基本资料</a></li>
				<li><a href="/user/pic_info" target="main_frame">头像设置</a></li>
				<li><a href="/user/user_follow" target="main_frame">我的关注</a></li>
				<li><a href="{{ url_for('profile.pass_info') }}" target="main_frame">密码修改</a></li>
				<li><a href="{{ url_for('profile.collection') }}" target="main_frame">我的收藏</a></li>
				<li><a href="{{ url_for('profile.news_release') }}" target="main_frame">新闻发布</a></li>
				<li><a href="{{ url_for("profile.news_list") }}" target="main_frame">新闻列表</a></li>
			</ul>
		</div>

<div class="user_con fr">
			<iframe src="/user/base_info" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
		</div>
{% endblock %}







{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#	<meta charset="UTF-8">#}
{#	<title>用户中心</title>#}
{#	<link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">#}
{#	<link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">#}
{#	<script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>#}
{#	<script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>#}
{#	<script type="text/javascript" src="../../static/news/js/main.js"></script>#}
{#</head>#}
{#<body>#}
{#	<div class="header_con">#}
{#		<div class="header">#}
{#			<a href="#" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>#}
{#			<div class="user_login fr" style="display: block;">#}
{#				<img src="../../static/news/images/user_pic.png" class="lgin_pic">#}
{#				<a href="#">用户张山</a>#}
{#				<a href="#">退出</a>#}
{#			</div>#}
{#		</div>#}
{#	</div>#}
{#	#}
{#	<div class="conter_con">#}
{#		<div class="user_menu_con fl">#}
{#			<div class="user_center_pic">#}
{#				<img src="../../static/news/images/user_pic.png" alt="用户图片">#}
{#			</div>#}
{#			<div class="user_center_name">用户张山</div>#}
{##}
{#			<ul class="option_list">#}
{#				<li class="active"><a href="../../static/news/html/user_base_info.html" target="main_frame">基本资料</a></li>#}
{#				<li><a href="../../static/news/html/user_pic_info.html" target="main_frame">头像设置</a></li>#}
{#				<li><a href="../../static/news/html/user_follow.html" target="main_frame">我的关注</a></li>#}
{#				<li><a href="../../static/news/html/user_pass_info.html" target="main_frame">密码修改</a></li>#}
{#				<li><a href="../../static/news/html/user_collection.html" target="main_frame">我的收藏</a></li>#}
{#				<li><a href="../../static/news/html/user_news_release.html" target="main_frame">新闻发布</a></li>#}
{#				<li><a href="../../static/news/html/user_news_list.html" target="main_frame">新闻列表</a></li>#}
{#			</ul>#}
{#		</div>#}
{##}
{#		<div class="user_con fr">#}
{#			<iframe src="../../static/news/html/user_base_info.html" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>#}
{#		</div>		#}
{#	</div>#}
{#	<div class="footer">		#}
{#		<div class="footer_links">#}
{#			<a href="">关于我们</a>#}
{#			<span>|</span>#}
{#			<a href="">联系我们</a>#}
{#			<span>|</span>#}
{#			<a href="">招聘人才</a>#}
{#			<span>|</span>#}
{#			<a href="">友情链接</a>#}
{#		</div>#}
{#		<p class="copyright">#}
{#			CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />#}
{#电话：010-****888    京ICP备*******8号#}
{#		</p>#}
{#	</div>#}
{#	#}
{#	<!-- 登录表单 -->#}
{#	<form class="login_form_con">#}
{#		<div class="login_form">#}
{#			<div class="login_title">#}
{#				<h3>登 录</h3>#}
{#				<a href="javascript:;" class="shutoff"></a>#}
{#			</div>#}
{#			<div class="form_group">				#}
{#				<input type="text" name="username" autocomplete="off">#}
{#				<div class="input_tip">用户名/手机号</div>#}
{#			</div>#}
{#			<div class="form_group">				#}
{#				<input type="password" name="password">#}
{#				<div class="input_tip">密码(不少于6位)</div>#}
{#			</div>#}
{#			<input type="submit" name="" value="登 录" class="input_sub">#}
{#			<div class="down_link">还没有账号？<a href="#" class="to_register">立即注册</a></div>#}
{#		</div>#}
{#		<div class="mask"></div>#}
{#	</form>#}
{#	#}
{#	<!-- 注册表单 -->#}
{#	<form class="register_form_con">#}
{#		<div class="register_form">#}
{#			<div class="register_title">#}
{#				<h3>注 册</h3>#}
{#				<a href="javascript:;" class="shutoff"></a>#}
{#			</div>#}
{#			<div class="form_group">				#}
{#				<input type="text" name="username" autocomplete="off" class="phone_input">#}
{#				<div class="input_tip">手机号</div>#}
{#				<div class="error_tip">手机号不能为空</div>#}
{#			</div>#}
{#			<div class="form_group">				#}
{#				<input type="password" name="code_pwd" class="code_pwd">#}
{#				<div class="input_tip">手机验证码</div>#}
{#				<a href="javascript:;" class="get_code">点击获取验证码</a>#}
{#				<div class="error_tip">验证码不能为空</div>#}
{#			</div>#}
{#			<div class="form_group">				#}
{#				<input type="password" name="password" class="pass_input">#}
{#				<div class="input_tip">密码(不少于6位)</div>#}
{#				<div class="error_tip">密码不能为空</div>#}
{#			</div>#}
{#			<div class="form_group">				#}
{#				<input type="password" name="code_pwd" class="code_pwd">#}
{#				<div class="input_tip">图形验证码</div>#}
{#				<img src="../../static/news/images/pic_code.png" class="get_pic_code">#}
{#				<div class="error_tip">图形码不能为空</div>#}
{#			</div>#}
{#			#}
{#			<div  class="form_group2 clearfix">#}
{#				<input type="checkbox" class="agree_input" checked>#}
{#				<p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>#}
{#				<div class="error_tip">请勾选</div>#}
{#			</div>#}
{#			<input type="submit" name="" value="注 册" class="input_sub">#}
{#			<div class="down_link">已有账号？<a href="#" class="to_login">立即登录</a></div>#}
{#		</div>#}
{#		<div class="mask"></div>#}
{#	</form>#}
{#</body>#}
{#</html>#}